name: Release Compiled PDF
on:
  push:
    branches:
      - main
    paths:
      - 'DevOps/DevOps.tex'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: DevOps
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTex document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: DevOps/DevOps.tex

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Rename file
        run: |
          mv DevOps.pdf Amogh_Tambad_Resume.pdf
      
      - name: Checkout main branch explicitly
        run: |
          git checkout main

      - name: Commit and Push PDF
        run: |
          git pull
          git add Amogh_Tambad_Resume.pdf
          git diff --quiet && echo "No changes to commit" && exit 0
          git commit -m "Compiled PDF on $(date -d "$M" '+%m')/$(date -d "$D" '+%d')/$(date -d "$Y" '+%Y') - $(date +%s)"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          
